FROM fedora:latest
# add parallel downloads
RUN  echo "[main]" > /etc/dnf/libdnf5.conf.d/80-user-settings.conf \ 
    && echo "max_parallel_downloads=10" >> /etc/dnf/libdnf5.conf.d/80-user-settings.conf

RUN dnf update -y  \
    && dnf clean all

RUN curl -sSf https://install.surrealdb.com | sh

ENV TZ=Asia/Bangkok
