volumes:
  source_code:
services:
  python_aiml:
    build:
      context: .
      dockerfile: docker/fedora/python/Dockerfile.python-aiml
    restart: unless-stopped
    command: [ "tail", "-f", "/dev/null" ]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    volumes:
      - source_code:/root/workspace
      - ./tmp:/root/workspace/tmp
      - ~/.ssh:/root/.ssh
      - ./.tmux.conf:/root/.tmux.conf
