volumes:
  source_code:
  db:
services:
  dioxus_rust:
    build:
      context: .
      dockerfile: docker/fedora/dioxus/Dockerfile.dev
    restart: unless-stopped
    # command: [ "tail", "-f", "/dev/null" ]
    # entrypoint: ["tail", "-f", "/dev/null"]
    env_file:
      - .env
    environment:
      - DB_HOST=surrealdb
      - DB_PORT=8000
      - DB_NAMESPACE=$DB_NAMESPACE
      - DB_DBNAME=$DB_DBNAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    volumes:
      - source_code:/root/workspace
      # - ~/.ssh:/root/.ssh:z
      # - ./.tmux.conf:/root/.tmux.conf:z
      # - ~/.config/helix:/root/.config/helix:z
      # - ./tmp:/root/tmp:z
  surrealdb:
    env_file:
      - .env
    image: surrealdb/surrealdb:latest
    restart: unless-stopped
    user: "0:0"
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      # - --bind
      # - 0.0.0.0:8000
      - rocksdb:/data/surreal/surreal.db
    ports:
      - 8000:8000
    volumes:
      - db:/data/surreal
  sqlserverdb:
    env_file:
      - .env
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    ports:
      - 1433:1433
    volumes:
      - db:/data/sqlserver
