volumes:
  source_code:
services:
  python:
    build:
      context: .
      dockerfile: docker/fedora/python/Dockerfile.python
    restart: unless-stopped
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - source_code:/root/workspace
      # - ./tmp:/root/workspace/tmp
      - ~/.ssh:/root/.ssh
      - ./.tmux.conf:/root/.tmux.conf
