volumes:
  source_code:
services:
  python_jupyter:
    build:
      context: .
      dockerfile: docker/fedora/python/Dockerfile.python-jupyter
    restart: unless-stopped
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - source_code:/root/workspace
      - ~/.ssh:/root/.ssh
      - ./.tmux.conf:/root/.tmux.conf
