volumes:
  source_code:
  db:
services:
  dioxus_rust:
    build:
      context: .
      dockerfile: docker/fedora/dioxus/Dockerfile.dev
    restart: unless-stopped
    # command: [ "tail", "-f", "/dev/null" ]
    # entrypoint: ["tail", "-f", "/dev/null"]
    env_file:
      - .env
    environment:
      - SURREAL_HOST=surrealdb
      - SURREAL_PORT=8000
      - SURREAL_NAMESPACE=$SURREAL_NAMESPACE
      - SURREAL_DBNAME=$SURREAL_DBNAME
      - SURREAL_USERNAME=$SURREAL_USERNAME
      - SURREAL_PASSWORD=$SURREAL_PASSWORD
      - MSSQL_HOST=sqlserverdb
      - MSSQL_PORT=1433
      - MSSQL_DBNAME=$MSSQL_DBNAME
      - MSSQL_USERNAME=$MSSQL_DBNAME
      - MSSQL_PASSWORD=$MSSQL_DBNAME
    volumes:
      - source_code:/root/workspace
      - ~/.ssh:/root/tmp
      # - ./.tmux.conf:/root/.tmux.conf:z
      # - ~/.config/helix:/root/.config/helix:z
      # - ./tmp:/root/tmp:z
  surrealdb:
    env_file:
      - .env
    image: surrealdb/surrealdb:latest
    restart: unless-stopped
    user: "0:0"
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - $SURREAL_USERNAME
      - --pass
      - $SURREAL_PASSWORD
      # - --bind
      # - 0.0.0.0:8000
      - rocksdb:/data/surreal/surreal.db
    ports:
      - 8000:8000
    volumes:
      - db:/data/surreal
  sqlserverdb:
    env_file:
      - .env
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: "0:0"
    restart: unless-stopped
    ports:
      - 1433:1433
    volumes:
      - db:/var/opt/mssql
