volumes:
  source_code:
services:
  dioxus_rust:
    build:
      context: .
      dockerfile: docker/fedora/dioxus/Dockerfile.dev
    restart: unless-stopped
    #command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - source_code:/root/workspace
      - ~/.ssh:/root/tmp
      # - ./.tmux.conf:/root/.tmux.conf
      # - ~/.config/helix:/root/.config/helix
      # - ./tmp:/root/tmp:z
    # ports:
    #   - "2222:22"
