volumes:
  source_code:
  db:
services:
  dioxus_rust:
    build:
      context: .
      dockerfile: docker/fedora/dioxus/Dockerfile.dev
    restart: unless-stopped
    # command: [ "tail", "-f", "/dev/null" ]
    # entrypoint: ["tail", "-f", "/dev/null"]
    environment:
      - DB_HOST=surrealdb
      - DB_PORT=8000
      - DB_NAMESPACE=$DB_NAMESPACE
      - DB_DBNAME=$DB_DBNAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    volumes:
      - source_code:/root/workspace
      - ~/.ssh:/root/.ssh:z
      - ./.tmux.conf:/root/.tmux.conf:z
      - ~/.config/helix:/root/.config/helix:z
      - ./tmp:/root/tmp:z
  surrealdb:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/fedora/surreal/Dockerfile.surreal
    restart: unless-stopped
    entrypoint: 
      - surreal 
      - start 
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - --bind
      - 0.0.0.0:8000
      - rocksdb:/var/lib/surreal/mydatabase.db
    ports:
      - 8000:8000
    volumes:
      - db:/var/lib/surreal

