volumes:
  python_dev:
services:
  jupyter:
    build:
      context: .
      dockerfile: docker/fedora/python/Dockerfile.python-jupyter
    restart: unless-stopped
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - python_dev:/root/workspace
