version: '3'
volumes:
  rust_zero2_prod_dev:
  db_zero2prod_dev:
services:
  rust_zero2_prod:
    build:
      context: .
      dockerfile: docker/Dockerfile.rust
    restart: on-failure
    command: [ "tail", "-f", "/dev/null" ]
    environment:
      - DATABASE_URL=postgres://postgres:password@db_zero2_prod:5432/newsletter
    volumes:
      - rust_zero2_prod_dev:/root/scr
    depends_on:
      - db_zero2_prod
  db_zero2_prod:
    image: postgres:16-alpine3.18
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=newsletter
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - db_zero2prod_dev:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: on-failure
    depends_on:
      - db_zero2_prod
    ports:
      - 8080:8080
