version: '3'
volumes:
  qr_rust_dev:
  vue3_dev:
services:
  qr_rust:
    build:
      context: .
      dockerfile: docker/Dockerfile.rust
    restart: on-failure
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - qr_rust_dev:/root/scr
      - "C:/Users/younp/Projects/rust_doc/qr-backend:/root/scr/qr-backend/target/doc"
  vue3:
    build:
      context: .
      dockerfile: docker/Dockerfile.vue3
    restart: on-failure
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - vue3_dev:/root/src
