services:
  rust:
    build:
      context: .
      dockerfile: docker/Dockerfile.rust
    restart: on-failure
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - C:\Users\younp\Projects\dev_server\tmp:/root/tmp