version: '3'
volumes:
  qr_rust_dev:
  qr_vue3_dev:
  qr_db_dev:
services:
  qr_rust:
    build:
      context: .
      dockerfile: docker/Dockerfile.qr_rust
    restart: unless-stopped
    command: [ "tail", "-f", "/dev/null" ]
    environment:
      - MSSQL_HOST=dev_server-qr_db-1
      - MSSQL_USERNAME=sa
      - MSSQL_PASSWORD=F5z0f7HXVtR5
      - ESERVICE_URL=https://ipcs-core.ipthailand.go.th/api/oauth/external/userinfo
    volumes:
      - qr_rust_dev:/root/src
  qr_vue3:
    build:
      context: .
      dockerfile: docker/Dockerfile.vue3
    restart: unless-stopped
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - qr_vue3_dev:/root/src
  qr_db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=F5z0f7HXVtR5
    ports:
      - 1433:1433
    volumes:
      - qr_db_dev:/var/opt/mssql

