volumes:
  axum_rust_dev:
  db_dev:
services:
  axum_rust:
    build:
      context: .
      dockerfile: docker/Dockerfile.axum_rust
    restart: unless-stopped
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - axum_rust_dev:/root/src
  db:
    image: postgres:16-alpine3.18
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - db_dev:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=8081
    ports:
      - 8081:8081
