services:
  rust:
    build:
      context: .
      dockerfile: docker/Dockerfile.rust
    restart: unless-stopped
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - C:\Users\younp\Projects\dev_server\tmp:/root/mnt