services:
  pg:
    image: docker.io/timescale/timescaledb-ha:pg18
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/home/postgres/pgdata

  pgadmin:
    image: docker.io/dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - pg

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - 8000:3000
    volumes:
      - dbgate-data:/root/.dbgate
    # environment:
    #   CONNECTIONS: con1,con2,con3,con4
    #
    #   LABEL_con1: MySql
    #   SERVER_con1: mysql
    #   USER_con1: root
    #   PASSWORD_con1: TEST
    #   PORT_con1: 3306
    #   ENGINE_con1: mysql@dbgate-plugin-mysql
    #
    #   LABEL_con2: Postgres
    #   SERVER_con2: postgres
    #   USER_con2: postgres
    #   PASSWORD_con2: TEST
    #   PORT_con2: 5432
    #   ENGINE_con2: postgres@dbgate-plugin-postgres
    #
    #   LABEL_con3: MongoDB
    #   URL_con3: mongodb://mongo:27017
    #   ENGINE_con3: mongo@dbgate-plugin-mongo
    #
    #   LABEL_con4: SQLite
    #   FILE_con4: /home/jan/feeds.sqlite
    #   ENGINE_con4: sqlite@dbgate-plugin-sqlite

volumes:
  pg_data:
  pgadmin_data:
  minio_data:
  dbgate-data:
