FROM alpine:3.18
WORKDIR /root/.config
ENV LANG=en_IN.UTF-8
ENV LANG=en_IN.UTF-8
RUN apk add --no-cache git \ 
    neovim \
    fd \
    unzip \
    curl \
    wget \
    tar \
    gzip \
    gcc \
    musl-dev \
    tmux \
    wl-clipboard && \
    git clone https://github.com/tawansongsang/nvim.git nvim && \
    git clone https://github.com/tawansongsang/tmux.git tmux

WORKDIR /root/src

