FROM fedora:latest

# add parallel downloads
RUN  echo "[main]" > /etc/dnf/libdnf5.conf.d/80-user-settings.conf \ 
    && echo "max_parallel_downloads=10" >> /etc/dnf/libdnf5.conf.d/80-user-settings.conf

# install base packages for rust developer
RUN dnf update -y \
    && dnf in git ripgrep tmux \
    python3 \
    python3-ipykernel \
    -y

# Setup variable environment
ENV TZ=Asia/Bangkok

WORKDIR /root/workspace

