FROM fedora:latest
# add parallel downloads
RUN  echo "[main]" > /etc/dnf/libdnf5.conf.d/80-user-settings.conf \ 
    && echo "max_parallel_downloads=10" >> /etc/dnf/libdnf5.conf.d/80-user-settings.conf

RUN dnf update -y \
    && dnf in nginx\
    -y

ENV TZ=Asia/Bangkok

RUN rm -rf /usr/share/nginx/html

COPY ./src/public /usr/share/nginx/html
COPY ./nginx/base.conf /etc/nginx/conf.d/
COPY ./nginx/spa.conf /etc/nginx/default.d/

EXPOSE 80

ENTRYPOINT [ "nginx" , "-g", "daemon off;" ]