FROM fedora:latest as rust
# add parallel downloads
RUN  echo "[main]" > /etc/dnf/libdnf5.conf.d/80-user-settings.conf \ 
    && echo "max_parallel_downloads=10" >> /etc/dnf/libdnf5.conf.d/80-user-settings.conf
# install base packages for rust developer
RUN dnf update -y \
    && dnf in git ripgrep bat tmux nginx \
    helix wl-clipboard \
    lldb rust-lldb \
    cargo clippy rustup rust-doc rustfmt rust-analyzer \
    rust-src rust-std-static-wasm32-unknown-unknown \
    -y

# Setup variable environment
ENV TZ=Asia/Bangkok \
    RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH

# install cargo-binstall
RUN curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

# final images
FROM rust as dev

RUN cargo binstall dioxus-cli
RUN dnf in nodejs npm -y
RUN npm install -g tailwindcss @tailwindcss/cli @tailwindcss/language-server vscode-langservers-extracted

WORKDIR /root/workspace

ENTRYPOINT [ "nginx" , "-g", "daemon off;" ]
