FROM quay.io/fedora/fedora:latest AS rust
# add parallel downloads
RUN  echo "[main]" > /etc/dnf/libdnf5.conf.d/80-user-settings.conf \
    && echo "max_parallel_downloads=10" >> /etc/dnf/libdnf5.conf.d/80-user-settings.conf
# install base packages for rust developer
RUN dnf update -y \
    && dnf group install development-tools -y \
    && dnf in glibc-langpack-th glibc-langpack-en \
    git ripgrep bat unzip \
    # tmux \
    nginx \
    # helix wl-clipboard \
    # openssh-server \
    # lldb rust-lldb \
    openssl-devel \
    # javascriptcoregtk4.1-devel rust-glib-sys-devel libsoup3-dvel \
    # rust-atk-devel \
    cargo clippy rustup rust-doc rustfmt rust-analyzer \
    rust-src rust-std-static-wasm32-unknown-unknown \
    -y

RUN mkdir -p /root/.cargo/bin/

# RUN ssh-keygen -A \
#     # && echo "UsePAM yes" > /etc/ssh/sshd_config.d/99-docker-ssh.conf \
#     && echo "PermitRootLogin yes" >> /etc/ssh/sshd_config.d/99-docker-ssh.conf \
#     # && sed -ri 's/^#?PermitRootLogin .*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config \
#     # && echo "PasswordAuthentication no" >> 99-docker-ssh.conf \
#     && echo "root:root" | chpasswd \
#     && touch /root/.ssh/authorized_keys \
#     && mkdir -p /root/.bashrc.d

# Setup variable environment
ENV TZ=Asia/Bangkok \
    RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:/root/.cargo/bin:$PATH \
    LANG=th_TH.utf8 \
    LC_ALL=th_TH.utf8

#COPY /docker/fedora/dioxus/01_basic_env /root/.bashrc.d/

# install cargo-binstall
# RUN curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

# install dioxus
RUN curl -sSL http://dioxus.dev/install.sh | sh

WORKDIR /root/workspace

# EXPOSE 22
# ENTRYPOINT [ "/usr/sbin/sshd", "-D" ]
ENTRYPOINT [ "nginx" , "-g", "daemon off;" ]

# final images
# FROM rust AS dev

# RUN cargo binstall dioxus-cli
# RUN dnf in nodejs npm -y
# RUN npm install -g tailwindcss @tailwindcss/cli @tailwindcss/language-server vscode-langservers-extracted

# WORKDIR /root/workspace

# EXPOSE 22
# ENTRYPOINT [ "nginx" , "-g", "daemon off;" ]
# ENTRYPOINT [ "/usr/sbin/sshd", "-D" ]
